// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpmOXvm8fwQ5Bv-aZgF-Q7vI_PLe_n-PY',
    appId: '1:474367438821:android:5cfebfd8e0bf2a08c0490c',
    messagingSenderId: '474367438821',
    projectId: 'trucker-389620',
    storageBucket: 'trucker-389620.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOQIf_cyAYzo1yNm66TqFVT4up86aVUWk',
    appId: '1:474367438821:ios:be0229d62039bd20c0490c',
    messagingSenderId: '474367438821',
    projectId: 'trucker-389620',
    storageBucket: 'trucker-389620.appspot.com',
    androidClientId: '474367438821-n524ioia0a4f40dpdv6976gkfa7ddo7r.apps.googleusercontent.com',
    iosClientId: '474367438821-uvjcnr4cfat6jdbeunrmk3i3hvf97ot3.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
